export const POSTS = [
    { id: 1, title: 'Post 1', content: 'This is the first post. Welcome to our blog!', image: 'https://picsum.photos/id/1/200/300' },
    { id: 2, title: 'Post 2', content: 'In this post, we will explore the wonders of JavaScript.', image: 'https://picsum.photos/id/2/200/300' },
    { id: 3, title: 'Post 3', content: 'Did you know? JavaScript was created in just 10 days.', image: 'https://picsum.photos/id/3/200/300' },
    { id: 4, title: 'Post 4', content: 'JavaScript is a high-level, interpreted programming language.', image: 'https://picsum.photos/id/4/200/300' },
    { id: 5, title: 'Post 5', content: 'JavaScript is characterized as dynamic, weakly typed, prototype-based and multi-paradigm.', image: 'https://picsum.photos/id/5/200/300' },
    { id: 6, title: 'Post 6', content: 'JavaScript runs on the client side of the web.', image: 'https://picsum.photos/id/6/200/300' },
    { id: 7, title: 'Post 7', content: 'JavaScript was influenced by programming languages such as Self and Scheme.', image: 'https://picsum.photos/id/7/200/300' },
    { id: 8, title: 'Post 8', content: 'JavaScript is used in many non-web environments like Adobe Acrobat, Node.js etc.', image: 'https://picsum.photos/id/8/200/300' },
    { id: 9, title: 'Post 9', content: 'JavaScript and Java are similar in some ways but fundamentally different in some others.', image: 'https://picsum.photos/id/9/200/300' },
    { id: 10, title: 'Post 10', content: 'The syntax of JavaScript is the set of rules that define a correctly structured JavaScript program.', image: 'https://picsum.photos/id/10/200/300' },
    { id: 11, title: 'Post 11', content:'The standards for JavaScript are the ECMAScript Language Specification (ECMA-262) and the ECMAScript Internationalization API specification (ECMA-402).',image:'https://picsum.photos/id/11/200/300'},
    { id :12 ,title:'post12' ,content:'As of December 2021, all modern browsers fully support ECMAScript 6 (known as ES2015) and ECMAScript 7 (known as ES2016).',image:'https://picsum.photos/id/12/200/300'},
    {id :13 ,title:'post13' ,content:'JavaScript has remained among the most popular and widely used programming languages.',image:'https://picsum.photos/id/13/200/300'},
    {id :14 ,title:'post14' ,content:'JavaScript has an API for working with text, arrays, dates and regular expressions.',image:'https://picsum.photos/id/14/200/300'},
    {id :15 ,title:'post15' ,content:'JavaScript does not have any built-in support for networking applications such as TCP or UDP.',image:'https://picsum.photos/id/15/200/300'},
    {id :16 ,title:'post16' ,content:'JavaScript assumes the ECMAScript standard and adds APIs to support HTML and XML documents manipulation and to deal with graphical user interface events.',image:'https://picsum.photos/id/16/200/300'},
    {id :17 ,title:'post17' ,content:'JavaScript engines were originally used only in web browsers, but they are now embedded in some servers like Node.js or Apache CouchDB.',image:'https://picsum.photos/id/17/200/300'},
    {id :18 ,title:'post18' ,content:'JavaScript is also used in environments that are not web-based like PDF documents or desktop widgets.',image:'https://picsum.photos/id/18/200/300'},
    {id :19 ,title:'post19' ,content:'Newer and faster JavaScript VMs and frameworks built upon them have also increased the popularity of JavaScript for server-side web applications.',image:'https://picsum.photos/id/19/200/300'},
    {id :20 ,title:'post20' ,content:'There are several community-driven websites actively maintained by JavaScript developers such as JSConf and Node Summit.',image:'https://picsum.photos/id/20/200/300'},
    {id :21 ,title:'post21' ,content:"There's a lot more to learn about JavaScript. Keep exploring!",image:'https://picsum.photos/id/21/200/300'},
    {id :22 ,title:'post22' ,content:'JavaScript has a number of frameworks and libraries that make it even more versatile.',image:'https://picsum.photos/id/22/200/300'},
    {id :23 ,title:'post23' ,content:'Some popular JavaScript frameworks are AngularJS ,ReactJS ,VueJS etc',image:'https://picsum.photos/id/23/200/300'},
    {id :24 ,title:'post24' ,content:'Some popular libraries of JavaScript are jQuery,D3.js,Lodash etc',image:'https://picsum.photos/id/24/200/300'},
    {id :25 ,title:'post25' ,content:'This is the last post in our series. Thank you for reading!',image:'https://picsum.photos/id/25/200/300'}
]
